<a href="https://colab.research.google.com/github/uzair011/Advance-python/blob/main/theIndex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

Every Series or DataFrame has an index. it isn't just the row labels for data.

In [3]:
url = "https://datascience.quantecon.org/assets/data/wdi_data.csv"
df = pd.read_csv(url)
df.info()

df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   country      72 non-null     object
 1   year         72 non-null     int64
 2   GovExpend    72 non-null     float64
 3   Consumption  72 non-null     float64
 4   Exports      72 non-null     float64
 5   Imports      72 non-null     float64
 6   GDP          72 non-null     float64
dtypes: float64(5), int64(1), object(1)
memory usage: 4.1+ KB

          country  year  GovExpend  Consumption   Exports   Imports        GDP
0          Canada  2017   0.372665     1.095475  0.582831  0.600031   1.868164
1          Canada  2016   0.364899     1.058426  0.576394  0.575775   1.814016
2          Canada  2015   0.358303     1.035208  0.568859  0.575793   1.794270
3          Canada  2014   0.353485     1.011988  0.550323  0.572344   1.782252
4          Canada  2013   0.351541     0.986400  0.518040  0.558636   1.732714
..            ...   ...        ...          ...       ...       ...        ...
67  United States  2004   2.267999     9.311431  1.335978  2.108585  13.846058
68  United States  2003   2.233519     8.974708  1.218199  1.892825  13.339312
69  United States  2002   2.193188     8.698306  1.192180  1.804105  12.968263
70  United States  2001   2.112038     8.480461  1.213253  1.740797  12.746262
71  United States  2000   2.040500     8.272097  1.287739  1.790995  12.620268

[72 rows x 7 columns]

In [5]:
df_small = df.head(6)
df_small

  country  year  GovExpend  Consumption   Exports   Imports       GDP
0  Canada  2017   0.372665     1.095475  0.582831  0.600031  1.868164
1  Canada  2016   0.364899     1.058426  0.576394  0.575775  1.814016
2  Canada  2015   0.358303     1.035208  0.568859  0.575793  1.794270
3  Canada  2014   0.353485     1.011988  0.550323  0.572344  1.782252
4  Canada  2013   0.351541     0.986400  0.518040  0.558636  1.732714
5  Canada  2012   0.354342     0.961226  0.505969  0.547756  1.693428

In [8]:
df_selected = df.iloc[[0, 1, 3, 71], :]
df_selected

          country  year  GovExpend  Consumption   Exports   Imports        GDP
0          Canada  2017   0.372665     1.095475  0.582831  0.600031   1.868164
1          Canada  2016   0.364899     1.058426  0.576394  0.575775   1.814016
3          Canada  2014   0.353485     1.011988  0.550323  0.572344   1.782252
71  United States  2000   2.040500     8.272097  1.287739  1.790995  12.620268

In [10]:
imp_exp = df_selected[["Exports", "Imports"]]
imp_exp_copy = imp_exp.copy()
imp_exp_copy

     Exports   Imports
0   0.582831  0.600031
1   0.576394  0.575775
3   0.550323  0.572344
71  1.287739  1.790995

In [11]:
imp_exp + imp_exp_copy

     Exports   Imports
0   1.165661  1.200063
1   1.152787  1.151550
3   1.100646  1.144688
71  2.575478  3.581991

In [12]:
df_selected

          country  year  GovExpend  Consumption   Exports   Imports        GDP
0          Canada  2017   0.372665     1.095475  0.582831  0.600031   1.868164
1          Canada  2016   0.364899     1.058426  0.576394  0.575775   1.814016
3          Canada  2014   0.353485     1.011988  0.550323  0.572344   1.782252
71  United States  2000   2.040500     8.272097  1.287739  1.790995  12.620268